# Generated by Django 4.2.23 on 2025-08-10 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('mobile_number', models.CharField(max_length=15, verbose_name='Mobile Number')),
                ('organization', models.CharField(max_length=100, verbose_name='Organization')),
                ('designation', models.CharField(max_length=100, verbose_name='Designation')),
                ('user_type', models.CharField(choices=[('SUPERUSER', 'Super User'), ('STAFF', 'Staff'), ('USER', 'Regular User')], default='USER', max_length=10, verbose_name='User Type')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(max_length=6, verbose_name='OTP Code')),
                ('purpose', models.CharField(choices=[('LOGIN', 'Login'), ('ACTIVATION', 'Account Activation'), ('PASSWORD_RESET', 'Password Reset')], default='LOGIN', max_length=15, verbose_name='Purpose')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(verbose_name='Expires At')),
                ('is_used', models.BooleanField(default=False, verbose_name='Used Status')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Used At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'OTP Code',
                'verbose_name_plural': 'OTP Codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True, verbose_name='Token')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='NULL for staff tokens (no expiry)', null=True, verbose_name='Expires At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='Last Used')),
                ('device_info', models.TextField(blank=True, null=True, verbose_name='Device Information')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Authentication Token',
                'verbose_name_plural': 'Authentication Tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserStaffAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Assignment Active')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Assignment Notes')),
                ('assigned_by', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'SUPERUSER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to=settings.AUTH_USER_MODEL, verbose_name='Assigned By')),
                ('staff', models.ForeignKey(limit_choices_to={'user_type': 'STAFF'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_users', to=settings.AUTH_USER_MODEL, verbose_name='Staff Member')),
                ('user', models.ForeignKey(limit_choices_to={'user_type': 'USER'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_staff', to=settings.AUTH_USER_MODEL, verbose_name='Regular User')),
            ],
            options={
                'verbose_name': 'Staff-User Assignment',
                'verbose_name_plural': 'Staff-User Assignments',
                'ordering': ['-assigned_at'],
                'unique_together': {('staff', 'user')},
            },
        ),
    ]
