# Generated by Django 4.2.23 on 2025-08-10 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstaffassignment',
            name='staff',
            field=models.ForeignKey(limit_choices_to={'user_type__in': ['STAFF', 'SUPERUSER']}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_users', to=settings.AUTH_USER_MODEL, verbose_name='Staff Member'),
        ),
    ]
